// Stub Data Connect function. Normally, this would be generated by the Firebase CLI.
async function getChatMessage({ chatMessageId }: { chatMessageId: string }): Promise<{ data: { chatMessage?: { content?: string } } }> {
  return {
    data: {
      chatMessage: {
        content: ""
      }
    }
  };
}

// [START fdc_forward_to_email_resolver]
import { getAuth } from "firebase-admin/auth";
import {
    FirebaseContext,
    GraphqlServerOptions,
    onGraphRequest
} from "firebase-functions/dataconnect/graphql";

const opts: GraphqlServerOptions = {
 schemaFilePath: "dataconnect/schema_resolver/schema.gql",
 resolvers: {
   query: {
     async forwardToEmail(
       _parent: unknown,
       args: Record<string, unknown>,
       _contextValue: FirebaseContext,
       _info: unknown
     ) {
       const chatMessageId = args.chatMessageId as string;

       let decodedToken;
       try {
         decodedToken = await getAuth().verifyIdToken(_contextValue.auth.token ?? "");
       } catch (error) {
         return false;
       }

       const email = decodedToken.email;
       if (!email) {
         return false;
       }

       // Call generated admin SDK.
       const response = await getChatMessage({chatMessageId});
       const messageContent = response.data.chatMessage?.content;

       // Here you call the cloud service of your choice to send the email with
       // the message content.

       return true;
     }
   },
 },
};

export const resolver = onGraphRequest(opts);
// [END fdc_forward_to_email_resolver]
